import { BaseLayout } from "@source/components/layouts/base-layout";
import { Provider } from "@source/components/ui/provider";
import { Toaster } from "@source/components/ui/toaster";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body style={{ background: "colors.syndex.background" }}>
        <Provider>
          <BaseLayout>
            {children}
            <Toaster />
          </BaseLayout>
        </Provider>
      </body>
    </html>
  );
}
